Update TailsGenerator.java
tiuczk-czw8/lab_0 pull request #7
Opened 2019-10-25 20:56 UTC by sticz1234

2019-10-31 07:47 UTC, radamuspl requested changes

2019-10-31 07:47 UTC, radamuspl commented on src/main/java/edu/iis/mto/lab_0/TailsGenerator.java
> +        	//System.out.println(value);	//Sprawdzenie
Nie powino się zostsawiać zakomentowanego kodu. Proszę usunąć tą linię.

2019-10-31 16:37 UTC, sticz1234 commented on src/main/java/edu/iis/mto/lab_0/TailsGenerator.java
> +        	//System.out.println(value);	//Sprawdzenie
Szanowny Panie Doktorze,
Załączam poprawiony plik.

2019-11-01 09:49 UTC, radamuspl approved these changes

2019-11-01 09:49 UTC, merged